Repository ComicScrip/locab, pull requests merged in 2022-07, with the labels that each got.

#41 Add products
  .env.example
  components/AddProductsPopUp.js
  components/LayoutAdmin.js
  components/ValidateDelete.js
  components/backoffice/ProductsRow.js
  components/backoffice/SearchProducts.js
  cypress.json
  cypress/fixtures/lit.jpeg
  cypress/integration/backProducts.spec.js
  cypress/integration/productsAdmin.spec.js
  cypress/integration/profileOrders.spec.js
  cypress/plugins/index.js
  cypress/support/index.js
  models/priceCategory.js
  models/product.js
  next.config.js
  package.json
  pages/_app.js
  pages/admin/index.js
  pages/admin/produits/edit/[id].js
  pages/api/priceCategory/index.js
  pages/api/products/[id].js
  pages/api/products/index.js
  prisma/migrations/20220627102646_modify_tables_according_to_client/migration.sql
  prisma/schema.prisma
  prisma/seed.js
  public/icons/annule.png
  public/icons/valide.png
  public/image/products/lit.jpeg
  styles/AddProductsPopUp.module.css
  styles/BackProduits.module.css
  styles/EditProduct.module.css
  styles/LayoutAdmin.module.css
  styles/ValidateDelete.module.css
  styles/globals.css
  yarn.lock
Labels: Ready for validation

#51 Back price
  components/LayoutAdmin.js
  components/backoffice/AddPricePopUp.js
  components/backoffice/PriceRow.js
  components/backoffice/SearchPrice.js
  cypress/integration/priceAdmin.spec.js
  cypress/plugins/index.js
  models/priceCategory.js
  pages/admin/prix/edit/[id].js
  pages/admin/prix/index.js
  pages/api/priceCategory/[id].js
  pages/api/priceCategory/index.js
  styles/AddPricePopUp.module.css
Labels: Fixed - ready for prod

#52 Product page
  .vscode/settings.json
  models/product.js
  pages/admin/produits/edit/[id].js
  pages/api/users/reset-password.js
  public/locales/en/NewPassword.json
  public/locales/fr/NewPassword.json
  public/locales/fr/signIn.json
  styles/EditProduct.module.css
  yarn.lock
Labels: Ready for prod

#48 Back client
  .env.example
  components/AddCustomersPopUp.js
  components/LayoutAdmin.js
  components/backoffice/CustomersRow.js
  components/backoffice/NavCustomers.js
  components/backoffice/SearchCustomers.js
  cypress/integration/customerAdmin.spec.js
  cypress/plugins/index.js
  models/user.js
  pages/admin/customers/edit/[id].js
  pages/admin/customers/index.js
  pages/api/orders/[id].js
  pages/api/orders/index.js
  pages/api/users/[id].js
  pages/api/users/index.js
  styles/AddCustomer.module.css
  styles/BackCustomers.module.css
  styles/EditUser.module.css
Labels: Fixed - ready for prod

#61 add some correction
  pages/admin/prix/edit/[id].js
  pages/admin/produits/edit/[id].js
  pages/profile/orders/index.js
  prisma/seed.js
  styles/BackCustomers.module.css
  styles/EditPrice.module.css
Labels: Ready for prod

#76 Correction rayane
  pages/commande/index.js
  public/locales/en/order.json
  public/locales/fr/order.json
  styles/Welcome.module.css
Labels: Ready for prod
